<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TecSight.Core\TecSight.Core.csproj" />
    <PackageReference Include="Vanara.PInvoke.DwmApi" Version="4.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Assets\tecsight.ico</ApplicationIcon>
    <Version>2.1.0</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\tecsight.ico" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TecSight.Core.Tests" />
  </ItemGroup>
</Project>
